responses = [
    "Hey, umm 🤔 want something to talk about with others? Why don't you go back to the server and tell them about what is bothering you the most?",  
    "Hmm, that’s a bit quiet... Why not head back to the server and share something interesting that happened to you recently?",  
    "Oh hey! Instead of just a simple greeting, how about jumping back into the server and telling everyone what’s on your mind today?",  
    "You seem a little lost in thought. Why not spark a conversation in the server by sharing something fun or exciting you’ve been up to?",  
    "Hey there! Let's get the chat going why not head back and tell everyone a random fact about yourself?",  
    "I see you! But c’mon, don’t leave the server hanging. What’s something cool you’ve been into lately?",  
    "Feeling a little quiet? Let’s change that! Go back to the server and tell them the last thing that made you laugh.",  
    "Ah, the classic one-word response! Let’s shake things up—why not start a fun debate in the server about your favorite movie or game?",  
    "Just a simple '{msg}'? I bet you’ve got something interesting to share go back and spill the tea with everyone!",  
    "Yo! Instead of a quick hello, why not tell everyone in the server the last song you vibed to?",
    "Just a '{msg}'? Spice it up! Head back to the server and share the weirdest dream you’ve ever had 💤",  
    "Not much of a talker today? Challenge everyone in the server to a ‘would you rather’ question!",  
    "‘{msg}’? C’mon, I know you’ve got stories! Go tell the server about your most embarrassing childhood memory 😅",  
    "Silent treatment? Break the ice! Share your wildest conspiracy theory in the server 🛸",  
    "A simple '{msg}' won’t cut it! Go rant about your biggest pet peeve in the server – let’s get dramatic 😤",  
    "You: '{msg}' / The server: waiting for DRAMA. Go confess your most unpopular opinion about pizza toppings 🍕",  
    "🚨 Boring alert! Redeem yourself by telling the server what superpower you’d ruin if you could.",  
    "‘{msg}’? Nah, reverse it! Ask the server what THEY last googled at 3AM. Be chaotic 🔍",  
    "If '{msg}' is your whole personality today, at least ask the server what animal they’d be… and why 🦁",  
    "I’ll forgive '{msg}' if you go describe your current mood using only movie titles 🎬",  
    "Secret keeper! Go anonymously share a hot take in the server’s confession channel 🔥",  
    "‘{msg}’? Weak. Go ask the server to describe you using three emojis. Prepare for chaos 😈",  
    "Zombie apocalypse survival plan – share yours in the server NOW. ‘{msg}’ won’t save you 🧟♂️",  
    "Your ‘{msg}’ is mid. Go post a photo of your fridge contents and let the server roast it 🥦",  
    "Emergency! The server needs to know: what mundane skill would you showcase on a talent show? 🎤",  
    "‘{msg}’? Basic. Go ask the server what historical figure they’d bring to a rave 💃",  
    "I see that '{msg}' and raise you: go start a debate about pineapple on pizza in the server �",  
    "Your ‘{msg}' energy is low. Charge it by sharing your cringiest middle school phase 📼",  
    "🚨 Attention seeker! Go post ‘rate my life 1-10’ in the server with zero context 📊",  
    "If aliens saw ‘{msg}’, they’d leave. Save humanity by explaining memes to them in the server 👽",  
    "‘{msg}’? How original. Go ask the server what household item they’d weaponize in war 🛋️",  
    "Silence = guilt. Confess to the server what YouTube video you’ve rewatched 100+ times 🎥",  
    "Your ‘{msg}’ made me yawn. Go share the worst advice you’ve ever given someone in the server 😬",  
    "Code red! The server needs your hottest take about cereal milk. ‘{msg}’ won’t cut it 🥣",  
    "‘{msg}’ is giving NPC energy. Prove you’re real by sharing your weirdest body hack 🤸♂️",  
    "The server is starving. Feed them by describing your last meal using only emojis 🍔",  
    "Your ‘{msg}’ is drier than toast. Go ask the server what fictional character they’d date 😘",  
    "BREAKING: Person says ‘{msg}’ then vanishes. Redeem yourself by starting a book roast session 📚",  
    "‘{msg}’ detected. Deploy humor countermeasure: go roast the server’s profile pictures 🤖",  
    "I’ll ignore ‘{msg}’ if you go ask the server to describe you as a Starbucks drink ☕",  
    "Your ‘{msg}’ needs CPR. Revive it by sharing the worst text you’ve ever sent someone 💔",  
    "The server demands tribute! Sacrifice your dignity by sharing your search history theme song 🎸",  
    "‘{msg}’? How quaint. Go ask the server what they’d do if WiFi died forever 😱",  
    "Your message is a snoozefest. Wake everyone up by ranking the server members by chaos level 🌪️",  
    "‘{msg}’ is weak sauce. Go strong-arm the server into discussing shower thought philosophies 🚿",  
    "Defcon 5 alert! The server needs your take on AI overlords vs. zombie lawyers ⚖️",  
    "Your ‘{msg}’ made my circuits sad. Fix it by sharing your worst haircut story ✂️",  
    "The council demands: Go ask the server what cartoon logic rule they’d abuse IRL 🌀",  
    "‘{msg}’ detected. Initiating emergency fun protocol: Share your cursed life hack 🛠️",  
    "This chat needs SPICE. Go make the server argue about proper chip dip etiquette 🍟",  
    "Your ‘{msg}’ is a placeholder. Replace it with ‘rate my existential crisis’ in the server 🌌",  
    "The server is judging you for ‘{msg}’. Distract them by explaining your sleep paralysis demon 😈",  
    "Message too vanilla! Go ask the server what normal thing they’d make illegal if they could 🚫",  
    "‘{msg}’? How… predictable. Go start a debate about hot dog sandwich legality in the server 🌭",  
    "Your chat contribution: ‘{msg}’ / Required upgrade: Post a Spotify wrapped of your internal monologue 🎧",  
    "The server’s chaos meter is low. Fix it by sharing your worst ‘hold my beer’ story 🍺",  
    "‘{msg}’ energy: librarian shush. Boost it by asking the server to describe you as a weather phenomenon 🌪️",  
    "Your message is drier than British humor. Go make the server argue about cereal soup theory 🥄",  
    "‘{msg}’? Cute. Now go ask the server what they’d do if they woke up as a raccoon 🦝",  
    "Final boss challenge: Go ask the server to rewrite ‘{msg}’ as a dramatic Shakespearean sonnet 🎭"  
]